sudo: required
dist: trusty
language: c

before_install:
    # update package list
    - sudo apt-get update -qq

install:
    # install implicit build dependencies
    - sudo apt-get install -qq --no-install-recommends build-essential fakeroot devscripts equivs
    # install build dependencies
    - sudo mk-build-deps --install debian/control -t "apt-get --yes --no-install-recommends"
    - sudo apt-get install -qq --no-install-recommends automake1.9
    # install
    - sudo add-apt-repository -y ppa:kalon33/gamesgiroll && sudo apt-get update && sudo apt-get install --only-upgrade autoconf

script:
    # build the debian package
    - dpkg-buildpackage -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc
#notifications:
#  email: false
